#!/bin/bash 
############################

PROG=`basename $0`
if [ $# -ne 4 ]
then
    echo "Usage: $PROG [strig to describe kind of analysis e.g. xe, azim, etc] "
    exit;
fi

function setenv(){ export $1=$2; }

setenv pyconfigname $1
setenv cardname $2
setenv GluonFilter $3
setenv comment  $4
#################################
# Output file locations
#################################
setenv Main_DIR     `pwd`
setenv DoWhat       JCIaaGF
setenv oname        JCIaaGF_pythia8230_pp2.76TeV_GF${GluonFilter}_$comment
setenv Disk         `pwd`
setenv OUT_ERRORS   $Disk/outputs/${oname}/errors
setenv Out_DIR      $Disk/outputs/${oname}/data
setenv LOG_DIR      $Disk/outputs/${oname}/logs
#################################
# Need for serial job in sepeli(pbs)
#################################
setenv noFileToRun 500
#################################

mkdir -p $OUT_ERRORS
mkdir -p $Out_DIR
mkdir -p $LOG_DIR

#################################
# Runlist to scan
#################################

# simplify this !!!
cat << EOF > exec_jtkt_$comment
#!/bin/bash -f
cd $Main_DIR
source setup.sh.puck
export what=$DoWhat
export sedN=1000
export iseg=\$SLURM_ARRAY_TASK_ID
sedN=\`expr \$sedN + \${iseg}\`
export outfile=$Out_DIR/$DoWhat-\$sedN.root
export Log=$LOG_DIR/$DoWhat-\$sedN.log
./\${what} \$outfile \$sedN 1000000 $pyconfigname $cardname ${GluonFilter}  >& \$Log
cd $Main_DIR
EOF
#\${what} \$outfile \$sedN 5000000 >& \$Log
chmod +x exec_jtkt_$comment
    sbatch -v --array=1-$noFileToRun exec_jtkt_$comment -J $comment  -e $OUT_ERRORS -o $OUT_ERRORS
