#! /bin/csh -f
find outputs | grep "$1" | perl -nle'/log$/ or next;open$F,$_;seek($F,-100,2);@L=<$F>;$N++;$L[-1]=~/Good/&&$G++;printf "$_ --- $L[-1]"}{ print "+"x40;print "finished=".($G+0)." running=$N";print"+"x40'
